"""
Video export utilities for text-to-video (T2V) model outputs.

This module provides functions to convert video tensors generated by T2V models
into standard video file formats (MP4, GIF) or image sequences.

Typical usage:
    from utils.video_export import tensor_to_video

    # After T2V inference
    video_frames, _ = inference_t2v(model, tokenizer, text_encoder, vae, prompt, device)

    # Export to video file
    tensor_to_video(video_frames, "output.mp4", fps=24)
"""

import tempfile
from pathlib import Path
from typing import List, Literal, Optional, Union

import numpy as np
import torch

try:
    from PIL import Image
except ImportError:
    Image = None


def tensor_to_video(
    video_tensor: torch.Tensor,
    output_path: Union[str, Path],
    fps: int = 24,
    quality: float = 8.0,
    bitrate: Optional[int] = None,
    value_range: Literal["auto", "[-1,1]", "[0,1]"] = "auto",
    batch_index: int = 0,
) -> str:
    """
    Convert a video tensor from T2V model to a video file.

    Args:
        video_tensor: Video tensor with shape [B, C, T, H, W] or [C, T, H, W].
                      C should be 3 (RGB channels).
        output_path: Output video file path (should end with .mp4).
        fps: Frames per second for output video. Default: 24.
        quality: Video quality (0-10, higher is better). Default: 8.0.
                 Uses variable bitrate encoding.
        bitrate: Optional constant bitrate in bits/second. If set, overrides quality.
        value_range: Expected value range of input tensor.
                     - "auto": Auto-detect based on min/max values
                     - "[-1,1]": Values in range [-1, 1] (typical for diffusion models)
                     - "[0,1]": Values in range [0, 1]
        batch_index: Which batch sample to export if batch_size > 1. Default: 0.

    Returns:
        str: Path to the saved video file.

    Raises:
        ImportError: If imageio or imageio-ffmpeg is not installed.
        ValueError: If tensor shape is invalid.

    Example:
        >>> video_tensor = model.generate(prompt)  # [1, 3, 21, 480, 720]
        >>> tensor_to_video(video_tensor, "output.mp4", fps=24)
    """
    try:
        import imageio
    except ImportError:
        raise ImportError(
            "imageio is required for video export. "
            "Install with: pip install imageio imageio-ffmpeg"
        )

    # Validate and reshape tensor
    video_tensor = _prepare_tensor(video_tensor, batch_index)

    # Convert value range to [0, 255] uint8
    frames = _tensor_to_frames(video_tensor, value_range)

    # Export using imageio
    output_path = str(output_path)
    with imageio.get_writer(
        output_path,
        fps=fps,
        quality=quality,
        bitrate=bitrate,
        macro_block_size=16,
    ) as writer:
        for frame in frames:
            writer.append_data(frame)

    return output_path


def tensor_to_gif(
    video_tensor: torch.Tensor,
    output_path: Union[str, Path],
    fps: int = 10,
    value_range: Literal["auto", "[-1,1]", "[0,1]"] = "auto",
    batch_index: int = 0,
    loop: int = 0,
    optimize: bool = True,
) -> str:
    """
    Convert a video tensor from T2V model to an animated GIF.

    Args:
        video_tensor: Video tensor with shape [B, C, T, H, W] or [C, T, H, W].
        output_path: Output GIF file path.
        fps: Frames per second. Default: 10 (GIFs typically use lower fps).
        value_range: Expected value range of input tensor.
        batch_index: Which batch sample to export if batch_size > 1.
        loop: Number of times to loop (0 = infinite). Default: 0.
        optimize: Whether to optimize GIF size. Default: True.

    Returns:
        str: Path to the saved GIF file.

    Example:
        >>> video_tensor = model.generate(prompt)
        >>> tensor_to_gif(video_tensor, "output.gif", fps=10)
    """
    if Image is None:
        raise ImportError(
            "Pillow is required for GIF export. Install with: pip install Pillow"
        )

    # Validate and reshape tensor
    video_tensor = _prepare_tensor(video_tensor, batch_index)

    # Convert to PIL images
    pil_frames = _tensor_to_pil_frames(video_tensor, value_range)

    # Calculate frame duration in milliseconds
    duration = int(1000 / fps)

    # Save as GIF
    output_path = str(output_path)
    pil_frames[0].save(
        output_path,
        save_all=True,
        append_images=pil_frames[1:],
        duration=duration,
        loop=loop,
        optimize=optimize,
    )

    return output_path


def tensor_to_frames(
    video_tensor: torch.Tensor,
    output_dir: Union[str, Path],
    format: Literal["png", "jpg", "jpeg"] = "png",
    prefix: str = "frame",
    value_range: Literal["auto", "[-1,1]", "[0,1]"] = "auto",
    batch_index: int = 0,
    quality: int = 95,
) -> List[str]:
    """
    Save video tensor as individual image frames.

    Args:
        video_tensor: Video tensor with shape [B, C, T, H, W] or [C, T, H, W].
        output_dir: Directory to save frames.
        format: Image format ("png", "jpg", or "jpeg"). Default: "png".
        prefix: Filename prefix. Default: "frame".
        value_range: Expected value range of input tensor.
        batch_index: Which batch sample to export if batch_size > 1.
        quality: JPEG quality (1-100). Only used for jpg/jpeg format.

    Returns:
        List[str]: Paths to all saved frame files.

    Example:
        >>> video_tensor = model.generate(prompt)
        >>> frame_paths = tensor_to_frames(video_tensor, "./frames/")
    """
    if Image is None:
        raise ImportError(
            "Pillow is required for image export. Install with: pip install Pillow"
        )

    # Validate and reshape tensor
    video_tensor = _prepare_tensor(video_tensor, batch_index)

    # Convert to PIL images
    pil_frames = _tensor_to_pil_frames(video_tensor, value_range)

    # Create output directory
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    # Save frames
    saved_paths = []
    num_digits = len(str(len(pil_frames)))

    for i, frame in enumerate(pil_frames):
        filename = f"{prefix}_{i:0{num_digits}d}.{format}"
        filepath = output_dir / filename

        save_kwargs = {}
        if format.lower() in ("jpg", "jpeg"):
            save_kwargs["quality"] = quality

        frame.save(filepath, **save_kwargs)
        saved_paths.append(str(filepath))

    return saved_paths


def tensor_to_numpy_frames(
    video_tensor: torch.Tensor,
    value_range: Literal["auto", "[-1,1]", "[0,1]"] = "auto",
    batch_index: int = 0,
    output_dtype: np.dtype = np.uint8,
) -> np.ndarray:
    """
    Convert video tensor to numpy array of frames.

    This is useful for custom processing or integration with other libraries.

    Args:
        video_tensor: Video tensor with shape [B, C, T, H, W] or [C, T, H, W].
        value_range: Expected value range of input tensor.
        batch_index: Which batch sample to export if batch_size > 1.
        output_dtype: Output numpy dtype. Default: np.uint8 (values 0-255).
                      Use np.float32 for normalized [0, 1] output.

    Returns:
        np.ndarray: Array of frames with shape [T, H, W, C].
                    - If output_dtype is uint8: values in [0, 255]
                    - If output_dtype is float32/float64: values in [0, 1]

    Example:
        >>> video_tensor = model.generate(prompt)
        >>> frames = tensor_to_numpy_frames(video_tensor)
        >>> print(frames.shape)  # (21, 480, 720, 3)
    """
    # Validate and reshape tensor
    video_tensor = _prepare_tensor(video_tensor, batch_index)

    # Normalize to [0, 1]
    frames = _normalize_tensor(video_tensor, value_range)

    # Rearrange from [C, T, H, W] to [T, H, W, C]
    frames = frames.permute(1, 2, 3, 0).cpu().numpy()

    if np.issubdtype(output_dtype, np.integer):
        # Convert to integer range
        max_val = np.iinfo(output_dtype).max
        frames = (frames * max_val).clip(0, max_val).astype(output_dtype)
    else:
        frames = frames.astype(output_dtype)

    return frames


# =============================================================================
# Internal Helper Functions
# =============================================================================


def _prepare_tensor(
    video_tensor: torch.Tensor,
    batch_index: int = 0,
) -> torch.Tensor:
    """
    Validate and prepare video tensor.

    Args:
        video_tensor: Input tensor with shape [B, C, T, H, W] or [C, T, H, W].
        batch_index: Which batch sample to use.

    Returns:
        torch.Tensor: Tensor with shape [C, T, H, W].
    """
    # Handle different input dimensions
    if video_tensor.dim() == 5:
        # [B, C, T, H, W] -> [C, T, H, W]
        if batch_index >= video_tensor.shape[0]:
            raise ValueError(
                f"batch_index {batch_index} out of range for tensor with "
                f"batch_size {video_tensor.shape[0]}"
            )
        video_tensor = video_tensor[batch_index]
    elif video_tensor.dim() == 4:
        # [C, T, H, W] - already correct shape
        pass
    else:
        raise ValueError(
            f"Expected 4D or 5D tensor, got {video_tensor.dim()}D tensor "
            f"with shape {video_tensor.shape}"
        )

    # Validate channel dimension
    if video_tensor.shape[0] != 3:
        raise ValueError(
            f"Expected 3 channels (RGB), got {video_tensor.shape[0]} channels. "
            f"Tensor shape: {video_tensor.shape}"
        )

    return video_tensor


def _normalize_tensor(
    video_tensor: torch.Tensor,
    value_range: Literal["auto", "[-1,1]", "[0,1]"],
) -> torch.Tensor:
    """
    Normalize tensor values to [0, 1] range.

    Args:
        video_tensor: Input tensor with shape [C, T, H, W].
        value_range: Expected value range.

    Returns:
        torch.Tensor: Normalized tensor with values in [0, 1].
    """
    if value_range == "auto":
        min_val = video_tensor.min().item()
        max_val = video_tensor.max().item()

        # Heuristic: if min < -0.5, assume [-1, 1] range
        if min_val < -0.5:
            value_range = "[-1,1]"
        else:
            value_range = "[0,1]"

    if value_range == "[-1,1]":
        # Convert from [-1, 1] to [0, 1]
        video_tensor = (video_tensor + 1) / 2
    # else: already in [0, 1]

    # Clamp to valid range
    video_tensor = video_tensor.clamp(0, 1)

    return video_tensor


def _tensor_to_frames(
    video_tensor: torch.Tensor,
    value_range: Literal["auto", "[-1,1]", "[0,1]"],
) -> List[np.ndarray]:
    """
    Convert video tensor to list of numpy frames.

    Args:
        video_tensor: Input tensor with shape [C, T, H, W].
        value_range: Expected value range.

    Returns:
        List[np.ndarray]: List of frames, each with shape [H, W, C] and dtype uint8.
    """
    # Normalize to [0, 1]
    video_tensor = _normalize_tensor(video_tensor, value_range)

    # Convert to uint8
    video_tensor = (video_tensor * 255).clamp(0, 255).to(torch.uint8)

    # Rearrange from [C, T, H, W] to list of [H, W, C]
    video_tensor = video_tensor.permute(1, 2, 3, 0)  # [T, H, W, C]
    video_tensor = video_tensor.cpu().numpy()

    frames = [video_tensor[i] for i in range(video_tensor.shape[0])]
    return frames


def _tensor_to_pil_frames(
    video_tensor: torch.Tensor,
    value_range: Literal["auto", "[-1,1]", "[0,1]"],
) -> List["Image.Image"]:
    """
    Convert video tensor to list of PIL images.

    Args:
        video_tensor: Input tensor with shape [C, T, H, W].
        value_range: Expected value range.

    Returns:
        List[PIL.Image.Image]: List of PIL images.
    """
    frames = _tensor_to_frames(video_tensor, value_range)
    return [Image.fromarray(frame) for frame in frames]


# =============================================================================
# Convenience Functions
# =============================================================================


def save_t2v_output(
    video_tensor: torch.Tensor,
    output_path: Union[str, Path],
    fps: int = 24,
    format: Optional[Literal["mp4", "gif", "frames"]] = None,
    **kwargs,
) -> Union[str, List[str]]:
    """
    High-level function to save T2V model output to various formats.

    Automatically detects format from file extension if not specified.

    Args:
        video_tensor: Video tensor with shape [B, C, T, H, W] or [C, T, H, W].
                      Expected value range: [-1, 1] (typical for diffusion models).
        output_path: Output path. Can be:
                     - A file path (e.g., "output.mp4", "output.gif")
                     - A directory path for frame export
        fps: Frames per second. Default: 24.
        format: Output format. If None, inferred from output_path extension.
        **kwargs: Additional arguments passed to the underlying export function.

    Returns:
        - For mp4/gif: str path to saved file
        - For frames: List[str] paths to saved frames

    Example:
        >>> video = model.generate("A cat playing")
        >>> save_t2v_output(video, "cat.mp4")  # -> "cat.mp4"
        >>> save_t2v_output(video, "cat.gif")  # -> "cat.gif"
        >>> save_t2v_output(video, "./frames/")  # -> ["./frames/frame_00.png", ...]
    """
    output_path = Path(output_path)

    # Infer format from path
    if format is None:
        suffix = output_path.suffix.lower()
        if suffix == ".mp4":
            format = "mp4"
        elif suffix == ".gif":
            format = "gif"
        elif suffix == "" or output_path.is_dir():
            format = "frames"
        else:
            raise ValueError(
                f"Cannot infer format from path '{output_path}'. "
                "Specify format explicitly or use .mp4/.gif extension."
            )

    # Export based on format
    if format == "mp4":
        return tensor_to_video(video_tensor, output_path, fps=fps, **kwargs)
    elif format == "gif":
        return tensor_to_gif(video_tensor, output_path, fps=fps, **kwargs)
    elif format == "frames":
        return tensor_to_frames(video_tensor, output_path, **kwargs)
    else:
        raise ValueError(f"Unknown format: {format}")
